### PR TITLE
Fix default map projection (use projection of OpenLayers)

### LINKED ISSUE #166: TileGrid shifts XYZ-Basemaps about 5km
It seems like the TileGrid change causes a shift of XYZ-Basemaps (~5km). The "standard" OSM Basemap via the custom OL-source is not affected. See GIF below.  Below also the layer definition in  `app-config.json`
When I remove the `tileGrid` Property in the `LayerFactory`, everything works as expected.
@justb4 

```javascript
  /**
   * Returns an XYZ based tile layer instance due to given config.
   *
   * @param  {Object} lConf  Layer config object
   * @return {ol.layer.Tile} OL XYZ layer instance
   */
  createXyzLayer (lConf) {
    const xyzLayer = new TileLayer({
      name: lConf.name,
      lid: lConf.lid,
      displayInLayerList: lConf.displayInLayerList,
      visible: lConf.visible,
      opacity: lConf.opacity,
      source: new XyzSource({
        url: lConf.url,
        attributions: lConf.attributions,
      //  tileGrid: lConf.tileGrid,  // <-- this probably causes the shift
        projection: lConf.projection
      })
    });
```

Peek 2021-01-28 21-01

Layer Definition of `app-config.json`:
```json
    {
      "type": "VECTOR",
      "lid": "gewerbe",
      "name": "Gewerbe Mutterstadt",
      "url": "./static/data/gewerbe.geojson",
      "format": "GeoJSON",
      "visible": true,
      "selectable": true,
      "style": {
        "radius": 4,
        "strokeColor": "purple",
        "strokeWidth": 2,
        "fillColor": "rgba(155,153,51,0.5)",
        "label": {
          "attribute": "title",
          "minResolution": 4.0,
          "outlineColor": "white",
          "outlineWidth": 2,
          "fillColor": "black",
          "offsetX": 0,
          "offsetY": 15,
          "align": "center"
        }
      }
    },
    {
      "type": "XYZ",
      "name": "Carto Positron",
      "url": "http://basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png",
      "lid": "positron",
      "displayInLayerList": true,
      "visible": true,
      "attributions": "© <a href='https://carto.com/attribution/' target='_blank'>CARTO</a> | <a href='https://openstreetmap.org/copyright' target='_blank'>© OpenStreetMap</a>-contributors | "
    }
```

### PR DESCRIPTION
**Pull request by chrismayer**
By introducing custom projections in Wegue (#82) , we set EPSG:3857 as default SRS of the map if nothing special has been defined. Therefore the projection has been declared in the code as `{code: 'EPSG:3857', units: 'm'}`, which differs from the projection definition of OpenLayers. This leads to an unwanted map shift in some edge cases (see #166).
  
This PR ensures that the definition of the default map projection ('EPSG:3857') - for the case that no special projection is defined
in the app-config - is derived by OpenLayers instead of defining it in the code.

Fixes #166

### CODE REVIEW

File: src/components/ol/Map.vue [hunk 1]
```diff
@@ -109,13 +110,14 @@ export default {
       olproj4(proj4);
     }
 
-    // Projection for Map, default is Web Mercator
+    // Projection for map, default is Web Mercator
+    let projection;
     if (!this.projection) {
```
Comment (JakobMiksch) [inline src/components/ol/Map.vue:115]: spontaneously I would turn around the if/else - e.g. `if (this.projection){ ... } else {}` 
I find  this more  readable. But that is pure eye-candy  ...

**Comment by JakobMiksch** [comment]
@chrismayer good catch finding the cause of the problem! the code looks fine and works for me. Only a minor non-blocking comment. Otherwise ready to merge.

**Review by JakobMiksch — APPROVED** [review]
