### PR TITLE
Fix feature selection with layer / feature hovering enabled

### LINKED ISSUE #193: Feature label prevents selection
The updated feature label https://github.com/meggsimum/wegue/commit/c922a04fe8b0e3ab0c232984ecfa2385dd3e4f5c prevents selecting a feature by clicking on it.

If I remove the `hoverAttribute` config in the appConfig, the selection works like expected.

Peek 2021-03-26 11-30

### PR DESCRIPTION
**Pull request by chrismayer**
This fixes the broken selection of a feature when the feature hovering is enabled. This error was introduced with #191.

Fixes #193

### CODE REVIEW

File: src/components/ol/Map.vue [hunk 1]
```diff
@@ -266,6 +266,8 @@ export default {
       // wrap the tooltip span in a OL overlay and add it to map
       me.overlay = new Overlay({
         element: overlayEl,
+        stopEvent: false,
+        className: 'wgu-hover-ol-overlay',
```
Comment (JakobMiksch) [inline src/components/ol/Map.vue:270]: why is `classname` necessary?
I cannot find a reference to it in the code base.

**Review by JakobMiksch — APPROVED** [review]
@chrismayer I tried it and now the selection works like expected. Just  one non-blocking question inline.

File: src/components/ol/Map.vue (hunk 1 above)
Comment (chrismayer) [reply src/components/ol/Map.vue:270]: See section `stopEvent` in https://openlayers.org/en/latest/apidoc/module-ol_Overlay-Overlay.html
